### ISSUE TITLE
Blank lines in YAML files are removed and single quotes replaced by double quotes

### ISSUE THREAD

**Issue by fdc-viktor-luft** [sethvargo/ratchet#35] opened 2022-08-25 06:27 UTC
### TL;DR

Running e.g. the "pin" command does some unwanted reformatting of the YAML files.

### Expected behavior

Keeping the preferred styles and just updating the one line containing the unpinned versions.

### Observed behavior

Running the "pin" command for instance on parts that look like this

```yaml
  ui-tests:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ui-tests
        name: 'Run UI Tests'
        with:
          gitCryptKey: ${{ secrets.GIT_CRYPT_KEY }}

  system-tests:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/system-tests
        name: 'Run System Tests'
        with:
          gitCryptKey: ${{ secrets.GIT_CRYPT_KEY }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```

Become this:

```yaml
  ui-tests:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3
      - uses: ./.github/actions/ui-tests
        name: "Run UI Tests"
        with:
          gitCryptKey: ${{ secrets.GIT_CRYPT_KEY }}
  system-tests:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3
      - uses: ./.github/actions/system-tests
        name: "Run System Tests"
        with:
          gitCryptKey: ${{ secrets.GIT_CRYPT_KEY }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```

### Version

0.3.0

### On what operating system are you using ratchet?

Linux

### CI/CD workflow file

```yaml
ui-tests:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ui-tests
        name: 'Run UI Tests'
        with:
          gitCryptKey: ${{ secrets.GIT_CRYPT_KEY }}

  system-tests:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/system-tests
        name: 'Run System Tests'
        with:
          gitCryptKey: ${{ secrets.GIT_CRYPT_KEY }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by sethvargo** [comment] 2022-08-25 12:59
This is a duplicate of https://github.com/sethvargo/ratchet/issues/14 and noted in the [README's known issues](https://github.com/sethvargo/ratchet#known-issues).

The [library we use to parse the YAML](https://pkg.go.dev/gopkg.in/yaml.v3) into an AST tree does not preserve whitespace or indentation, so unfortunately there's nothing Ratchet can do here. The original version of YAML did regex-based replacements on the file, but that proved to be extremely error-prone, so now it parses and re-renders the AST tree.

Please file issues against the upstream library at: https://github.com/go-yaml/yaml/issues/new

**Closed by sethvargo** 2022-08-25 12:59 UTC
Labels: bug

**Comment by fdc-viktor-luft** [comment] 2022-08-25 13:11
Thanks for your explanation. I've created a workaround for myself :+1:
